-- MySQL Script generated by MySQL Workbench
-- Wed Oct 22 08:07:37 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `kinesiologia` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kinesiologia` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `kinesiologia` ;

-- -----------------------------------------------------
-- Table `admins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `admins` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `admins` (
  `id_admins` INT NOT NULL AUTO_INCREMENT,
  `contrasenia` VARCHAR(45) NOT NULL,
  `fk_personas` INT NOT NULL,
  PRIMARY KEY (`id_admins`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_admins_UNIQUE` ON `admins` (`id_admins` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `fechas_horas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fechas_horas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `fechas_horas` (
  `id_fechas_horas` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  PRIMARY KEY (`id_fechas_horas`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_fechas_horas_UNIQUE` ON `fechas_horas` (`id_fechas_horas` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `metodos_pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `metodos_pago` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `metodos_pago` (
  `id_metodos_pago` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_metodos_pago`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_metodos_pago_UNIQUE` ON `metodos_pago` (`id_metodos_pago` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pago_sesiones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pago_sesiones` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pago_sesiones` (
  `fk_metodos_pago` INT NOT NULL,
  `fk_sesiones` INT NOT NULL,
  `monto` DECIMAL NOT NULL,
  PRIMARY KEY (`fk_metodos_pago`, `fk_sesiones`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `personas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `personas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `personas` (
  `id_personas` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `dni` INT NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `telefono` INT NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id_personas`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_personas_UNIQUE` ON `personas` (`id_personas` ASC) ;

SHOW WARNINGS;
CREATE UNIQUE INDEX `dni_UNIQUE` ON `personas` (`dni` ASC) ;

SHOW WARNINGS;
CREATE UNIQUE INDEX `email_UNIQUE` ON `personas` (`email` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `sesiones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sesiones` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `sesiones` (
  `id_sesiones` INT NOT NULL AUTO_INCREMENT,
  `detalles` TINYTEXT NULL,
  `imagen` VARCHAR(100) NULL,
  `fk_personas` INT NOT NULL,
  `fk_fechas_horas` INT NOT NULL,
  PRIMARY KEY (`id_sesiones`, `fk_fechas_horas`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_sesiones_UNIQUE` ON `sesiones` (`id_sesiones` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `sesiones_tratamientos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sesiones_tratamientos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `sesiones_tratamientos` (
  `fk_sesiones` INT NOT NULL,
  `fk_tratamientos` INT NOT NULL,
  PRIMARY KEY (`fk_sesiones`, `fk_tratamientos`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tratamientos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tratamientos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tratamientos` (
  `id_tratamientos` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tratamientos`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_tratamientos_UNIQUE` ON `tratamientos` (`id_tratamientos` ASC) ;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
